### ISSUE TITLE
How to run properly the script?

### ISSUE THREAD

**Issue by vash1981** [Frocioccolato/UnieuroBot#1]
Hi,
I've installed Python for windows and all the required modules but can't run the script without getting error after the initial check timeout request.
Error: 

_Traceback (most recent call last):
  File "C:\Unieuro\main.py", line 10, in <module>
    f = open("credenziali.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'credenziali.txt'_

Thanks

**Comment by carlott0** [comment]
Hi,
make sure you have put the file credenziali.txt in the same folder of Main.py  and changed it appropriately with your data

**Comment by vash1981** [comment]
Yep, the file "credenziali" and the other txt are into the same folder and properly configured. What command I have to use to run the script? Simply python.exe main.py?

-I'm using the latest python 3.9 setup for windows

**Comment by carlott0** [comment]
On windows i think you have to put the absolute path of python.exe and then Main.py, so it would be something like this
C:\Users\user\Programs\Python\Python38\python.exe Main.py and you have to run this command from the folder where there is Main.py

**Comment by vash1981** [comment]
Thanks so much I got the problem, was some spaces into the txt file, and now is running, there is any method to let the script continuosly check a not available product until it get on and then add it to the cart?

**Comment by carlott0** [comment]
Good job! My script when the product it's not available runs anyway
Try it putting an higher price of the real and let's see ;)

**Comment by vash1981** [comment]
If an higher price is set the script tries to add to cart and returns an error stopping. Is there a method to put it in loops without making it stop?
Something like, if the add to cart fails then restart the check in loop every (x) seconds.

**Comment by carlott0** [comment]
Sorry i mean lower, the price you insert in file unieuro.txt is the budget you have, you have to insert a lower value there
You can also try with a product that is not available

**Comment by vash1981** [comment]
ok, tryed now.
If a lower value is set the script goes in loop with "non è sceso di prezzo" but if the product is available it does not add it to the cart and repeat "non è sceso di prezzo" always.

**Comment by carlott0** [comment]
Yes it goes in the loop because it searches endlessly if it drops in price, if the product is not available or is priced higher than your budget then the print is the same, in the future I will change it with a distinction between them

**Comment by vash1981** [comment]
It would be very useful to check an unavailable product while waiting for it to become purchasable again. Like the damn RTX series I'm trying to buy :(

**Comment by carlott0** [comment]
you can still put a very high price in the file and then let it run, when it becomes available it adds it directly to the cart

**Comment by vash1981** [comment]
Unfortunately unieuro always shows the price of the product (even if not available) so the script always tries to add it then fails and stops.

**Comment by carlott0** [comment]
I fixed it, copy the new file Check.py and let's see.
Hope you enjoy ;)

**Comment by vash1981** [comment]
Awesome! great job indeed mate, works like a charm. I was able to find a "work around" for the previous problem and run it anyway, but this works much better now ;) So much clean

**Comment by carlott0** [comment]
Thanks I appreciate it!
